# Generated by Django 3.1.3 on 2020-11-11 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arret',
            old_name='geometry',
            new_name='coords',
        ),
        migrations.RemoveField(
            model_name='arret',
            name='equipement',
        ),
        migrations.AddField(
            model_name='arret',
            name='banc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arret',
            name='carte_trajets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arret',
            name='comment',
            field=models.CharField(default='aucun commentaire', max_length=100),
        ),
        migrations.AddField(
            model_name='arret',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arret',
            name='horaires',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arret',
            name='toit',
            field=models.BooleanField(default=False),
        ),
    ]
