# Generated by Django 3.1.3 on 2020-11-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201117_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arret',
            old_name='list_lignes',
            new_name='nom_lignesBis',
        ),
    ]
