# Generated by Django 3.1.3 on 2020-11-17 12:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201117_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arret',
            name='mes_choix',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SNK', 'SNK'), ('OnePiece', 'OPiece'), ('Naruto', 'Naruto'), ('Mounirito', 'Mounirito'), ('Kakashi', 'Kakashi')], max_length=100),
        ),
    ]
