# Generated by Django 3.1.3 on 2020-11-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201117_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arret',
            name='mes_choix',
        ),
    ]
